### ISSUE TITLE
dynamic-mappings loads env from environment, not config file

### ISSUE THREAD

**Issue by warrenronsiek** [muuki88/sbt-native-packager-examples#17]
The the dynamic mappings example project doesn't actually load the `env` value from the config files, instead it loads from the environment variable directly. The simplest way to see this to run `sbt -Denv=prod run` in the terminal and note that the output `This package runs in prod` is not what would be expected as `prod.conf` sets `env = production` and not `env = prod`.

**Comment by muuki88** [comment]
Thanks for the issue @warrenronsiek :smile: 

The idea behind this example is not that you can change the `application.conf` _mapping_ for the resulting package, not during `sbt run`. These are two very separate things.

This example only changes the `mappings in Universal`, but nothing inside the `run` command.

What are you trying to achieve? The example is pretty old and I would rather recommend shipping all configurations and start your application with a different `config.resource` parameter in different environments.
